language: python
python: "3.7"
dist: xenial

services:
  - docker

stages:
  - lint
  - test
  - name: deploy
    if: tag IS present

cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install -v

jobs:
  include:
    - stage: test
      install:
        - pip install --upgrade pip
        - pip install poetry
        - poetry install -v
      script:
        - make test
    - stage: deploy
      script:
        - echo Deploying to PyPI...

deploy:
  - provider: script
    script: |
      poetry version $(git describe --tags --abbrev=0)
      poetry publish --username $PYPI_PASS --password $PYPI_PASS --build
    on:
      repo: clarityai-eng/jsonschema2ddl
      branch: master
      python: '3.7'
      tags: true
